<Project Sdk="Microsoft.NET.Sdk.Razor">

	<PropertyGroup>
		<TargetFramework>net10.0</TargetFramework>
		<AddRazorSupportForMvc>true</AddRazorSupportForMvc>
		<Nullable>enable</Nullable>
		<ImplicitUsings>enable</ImplicitUsings>
		<GeneratePackageOnBuild>true</GeneratePackageOnBuild>
		<Version>2.0.0</Version>
		<Authors>Griesoft</Authors>
		<Owners>Griesoft,jooni91</Owners>
		<Company>Griesoft</Company>
		<Copyright>Griesoft</Copyright>
		<NeutralLanguage>en</NeutralLanguage>
		<PackageTags>Calendly;schedule meetings;OrchardCore;Module;Griesoft</PackageTags>
		<PackageReadmeFile>README.md</PackageReadmeFile>
		<PackageId>Griesoft.OrchardCore.Calendly</PackageId>
		<Title>Orchard Core Calendly Module</Title>
		<Description>A module designed for seamless integration of Calendly into your Orchard Core site.</Description>
		<PackageLicenseExpression>BSD-3-Clause</PackageLicenseExpression>
		<IncludeSymbols>true</IncludeSymbols>
		<SymbolPackageFormat>snupkg</SymbolPackageFormat>
		<GenerateDocumentationFile>True</GenerateDocumentationFile>
		<DocumentationFile>..\docs\Griesoft.OrchardCore.Calendly.xml</DocumentationFile>
		<RepositoryUrl>https://github.com/griesoft/Griesoft-OrchardCore-Calendly</RepositoryUrl>
		<PackageProjectUrl>https://github.com/griesoft/Griesoft-OrchardCore-Calendly</PackageProjectUrl>
		<PublishRepositoryUrl>true</PublishRepositoryUrl>
		<GenerateAssemblyConfigurationAttribute>false</GenerateAssemblyConfigurationAttribute>
		<GenerateAssemblyCompanyAttribute>false</GenerateAssemblyCompanyAttribute>
		<GenerateAssemblyProductAttribute>false</GenerateAssemblyProductAttribute>
	</PropertyGroup>

	<ItemGroup>
		<FrameworkReference Include="Microsoft.AspNetCore.App" />
	</ItemGroup>

	<ItemGroup>
		<None Include="..\README.md">
			<Pack>True</Pack>
			<PackagePath>\</PackagePath>
		</None>
	</ItemGroup>

	<ItemGroup>
		<PackageReference Include="OrchardCore.Module.Targets" Version="3.0.1" />
		<PackageReference Include="OrchardCore.ContentManagement" Version="3.0.1" />
		<PackageReference Include="OrchardCore.ResourceManagement" Version="3.0.1" />
	</ItemGroup>

	<ItemGroup>
		<PackageReference Include="StyleCop.Analyzers" PrivateAssets="all" Version="1.2.0-beta.556" />
	</ItemGroup>

</Project>
